name: work in crone ql 
on:
  schedule:
    - cron:  '10 */8 * * *'    
jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
      with:
        ref: ${{ github.head_ref }}
    - name: Only run this if exist in/fuql
      run: '(test -f in/*.fuql && echo fuql exists) ||  exit'                  
    - name: test codeql resolve languages
      run: |
          sudo apt-get install wget p7zip-full unzip 
          sudo wget -O /opt/codeql.zip https://github.com/github/codeql-cli-binaries/releases/download/v2.0.5/codeql.zip
          sudo 7z x /opt/codeql.zip -o/opt/
          sudo chmod -R 777 /opt/codeql/
          sudo /opt/codeql/codeql version
          sudo /opt/codeql/codeql resolve languages
          sudo /opt/codeql/codeql resolve qlpacks
          sudo git clone https://github.com/Semmle/ql.git /opt/ql
          cd insec/
          sudo 7z x archive.7z -p${{ secrets.GIT_PASS }} -o/opt/
          cd ..
          sudo apt-get install build-essential cmake git perl python3 autoconf automake libtool
          sudo python3 /opt/range1.py  in/ /opt/ out/ outql/ outqlfld/  
